# 04 One-sample and Two-sample test

## 01 One-sample test

### 1. One-sample t test

- <img src="https://latex.codecogs.com/svg.image?(x_1,\cdots,x_n)\sim&space;N(\mu,\sigma^2)"><br>
<img src="https://latex.codecogs.com/svg.image?H_0:\mu=\mu_0\;\;vs\;\;H_1:\mu\neq\mu_0">

- 검정통계량 <img src="https://latex.codecogs.com/svg.image?t_0=\frac{\bar{x}-\mu_0}{s/\sqrt{n}}\sim&space;t(n-1)">

ex) example concerning daily intake in kJ for 11 women(Altman, 1991, p.183). To investigate whether the women's energy intake deviates systematically from a recommended value of 7725kJ.<br>

예) 11명의 여성들의 일일 에너지 섭취량에 대한 예제를 살펴보겠습니다(Altman, 1991, p.183). 이 여성들의 에너지 섭취량이 권장값인 7725kJ에서 체계적으로 벗어나는지 조사하기 위해서입니다.


In [1]:
daily.intake <- c(5260, 5470, 5640, 6180, 6390, 6515, 6805, 7515, 7515, 8230, 8770)
mean(daily.intake)
sd(daily.intake)
quantile(daily.intake)

[1] 6753.636

[1] 1142.123

0%  25%  50%  75% 100% 
5260 5910 6515 7515 8770

In [2]:
t.test(daily.intake, mu=7725)


	One Sample t-test

data:  daily.intake
t = -2.8208, df = 10, p-value = 0.01814
alternative hypothesis: true mean is not equal to 7725
95 percent confidence interval:
 5986.348 7520.925
sample estimates:
mean of x 
 6753.636 


- You can immediately see that p<0.05 and thus that (using the customary 5% level of significance) data deviate significantly from the hypotheses that the mean is 7725.
- Optional arguments
  - mu (def=0)
  - alternative = "grater"("g") or "less"("l") (def=two-sided)
  - conf.level = 0.99 (def=0.95)

### 2. Wilcoxon signed-rank test

- The t tests are fairly robust against departures from the normal distribution especially in larger samples, but sometimes you wish to avoid making that sssumption. To this end, the distribution-free methods are convenient.
- t 검정은 특히 큰 샘플에서는 정규 분포에서 벗어난 경우에도 상당히 견고합니다. 하지만 때로는 그 가정을 피하고 싶을 수 있습니다. 이를 위해 비모수적인 방법들이 편리합니다.

- For the one-sample Wilcoxon test, the procedure is to subtract is to subtract the theoretical <img src="https://latex.codecogs.com/svg.image?\mu_0"> and rank the differences according to their numerical value, ignoring the sign, and then calculate the sum of the positive or negative ranks.
- 단일표본 Wilcoxon 검정에서의 절차는 이론적인 <img src="https://latex.codecogs.com/svg.image?\mu_0">를 빼고 그 차이를 숫자 값에 따라 순위를 매기되 부호를 무시하고, 그 다음 양수 또는 음수 순위의 합계를 계산하는 것입니다.

In [3]:
wilcox.test(daily.intake, mu=7725)

Warning message in wilcox.test.default(daily.intake, mu = 7725):
"tie가 있어 정확한 p값을 계산할 수 없습니다"



	Wilcoxon signed rank test with continuity correction

data:  daily.intake
V = 8, p-value = 0.0293
alternative hypothesis: true location is not equal to 7725


- The test statistic V is the sum of the positive ranks. In the example, the p-value is computed from the normal approximation because of the tie at 7515.
- 검정 통계량 V는 양수 순위의 합계입니다. 예제에서 7515에서의 동률로 인해 정규 근사를 사용하여 p값이 계산됩니다.

## 02 Two-sample test(Independent samples)

### 1. Two-sample test

- The two-sample t test is used to test the hypothesis that two samples may be assumed to come from distributions with the same mean <img src="https://latex.codecogs.com/svg.image?(\delta_0=0)">.
- 두 표본 t 검정은 두 표본이 동일한 평균 <img src="https://latex.codecogs.com/svg.image?(\delta_0=0)">을 가진 분포에서 추출되었을 것으로 가정하는 가설을 검정하는 데 사용됩니다.
- Hypothesis for comparing two population means <img src="https://latex.codecogs.com/svg.image?(\mu_1,\mu_2)">.

- ① <img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=\delta_0"> <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2>\delta_0">
- ② <img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=\delta_0"> <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2<\delta_0">
- ③ <img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=\delta_0"> <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2\neq\delta_0">

- If the sample size is sufficiently large (usually greater than 30), the following test statistic is used regardless of the population distribution(standard normal distribution).
- 표본 크기가 충분히 큰 경우 (일반적으로 30 이상), 모집단 분포에 관계없이 다음 검정 통계량이 사용됩니다(표준 정규분포).
  - <img src="https://latex.codecogs.com/svg.image?Z=\frac{(\bar{X_1}-\bar{X_2})-\delta_0}{\sqrt{\frac{S_1^2}{n_1}&plus;\frac{S_2^2}{n_2}}}">    

- If the sample size is small, under the assumption of normal distribution and equal variance we can use the following test statistics.
- 표본 크기가 작은 경우, 정규 분포를 가정하고 분산이 동일하다고 가정할 때 다음과 같은 검정 통계량을 사용할 수 있습니다.


|<img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=\delta_0"><br><img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2>\delta_0">|<img src="https://latex.codecogs.com/svg.image?\frac{(\bar{X_1}-\bar{X_2})-\delta_0}{\sqrt{\frac{S_p^2}{n_1}&plus;\frac{S_p^2}{n_2}}}>t_{n_1+n_2-2,\alpha} \Rightarrow reject\;H_0">|
|:-:|:-:|
|<img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=\delta_0"><br><img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2<\delta_0">|<img src="https://latex.codecogs.com/svg.image?\frac{(\bar{X_1}-\bar{X_2})-\delta_0}{\sqrt{\frac{S_p^2}{n_1}&plus;\frac{S_p^2}{n_2}}}<-t_{n_1+n_2-2,\alpha} \Rightarrow reject\;H_0">|
|<img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=\delta_0"><br><img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2\neq\delta_0">|<img src="https://latex.codecogs.com/svg.image?\left\|\frac{(\bar{X_1}-\bar{X_2})-\delta_0}{\sqrt{\frac{S_p^2}{n_1}&plus;\frac{S_p^2}{n_2}}}\right\|>t_{n_1&plus;n_2-2,\alpha/2}\Rightarrow&space;reject\;H_0">|

<br>
<img src="https://latex.codecogs.com/svg.image?S_p^2=\frac{(n_1-1)S_1^2&plus;(n_2-1)S_2^2}{n_1&plus;n_2-2}">

- If variances are not equal, we need to modify the degrees of freedom of the t distribution to *Φ*(Satterthwaite approximation)
- 분산이 동일하지 않은 경우, t 분포의 자유도를 Satterthwaite 근사치인 *Φ*로 수정해야 합니다.

|<img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=\delta_0"><br><img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2>\delta_0">|<img src="https://latex.codecogs.com/svg.image?\frac{(\bar{X_1}-\bar{X_2})-\delta_0}{\sqrt{\frac{S_1^2}{n_1}&plus;\frac{S_2^2}{n_2}}}>t_{\phi,\alpha} \Rightarrow reject\;H_0">|
|:-:|:-:|
|<img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=\delta_0"><br><img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2<\delta_0">|<img src="https://latex.codecogs.com/svg.image?\frac{(\bar{X_1}-\bar{X_2})-\delta_0}{\sqrt{\frac{S_1^2}{n_1}&plus;\frac{S_2^2}{n_2}}}<-t_{\phi,\alpha} \Rightarrow reject\;H_0">|
|<img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=\delta_0"><br><img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2\neq\delta_0">|<img src="https://latex.codecogs.com/svg.image?\left\|\frac{(\bar{X_1}-\bar{X_2})-\delta_0}{\sqrt{\frac{S_1^2}{n_1}&plus;\frac{S_2^2}{n_2}}}\right\|>t_{\phi,\alpha/2}\Rightarrow&space;reject\;H_0">|

<br>
<img src="https://latex.codecogs.com/svg.image?\phi=\frac{\left[\frac{S_1^2}{n_1}&plus;\frac{S_2^2}{n_2}\right]^2}{\frac{(S_1^2/n_1)^2}{n_1-1}&plus;\frac{(S_2^2/n_2)^2}{n_2-1}}">





- The two-sample t test is used to test the hypothesis that two samples may be assumed to come from distributions with the same mean.
- 두 표본 t 검정은 두 표본이 동일한 평균을 가진 분포에서 추출되었을 것으로 가정하는 가설을 검정하는 데 사용됩니다.

In [4]:
library(ISwR)
data(energy)
attach(energy)

t.test(expend~stature)

Warning message:
"패키지 'ISwR'는 R 버전 4.3.3에서 작성되었습니다"



	Welch Two Sample t-test

data:  expend by stature
t = -3.8555, df = 15.919, p-value = 0.001411
alternative hypothesis: true difference in means between group lean and group obese is not equal to 0
95 percent confidence interval:
 -3.459167 -1.004081
sample estimates:
 mean in group lean mean in group obese 
           8.066154           10.297778 


- The confidence interval is for the difference in means and does not contain 0, which is in accordance with the p-value indicating a significant difference at the 5% level.
- 신뢰 구간은 평균 차이에 대한 것으로, 0을 포함하지 않으며, 이는 5% 수준에서 유의한 차이를 나타내는 p값과 일치합니다.

- It is Welch's variant of the t test. This is the test where you do not assume that the variance is the same in the two groups, which(among other things) results in the fractional degrees of freedom.
- 이는 웰치의 t 검정의 변형입니다. 이는 두 그룹의 분산이 동일하다고 가정하지 않는 테스트로, 이로 인해 분수 자유도가 발생합니다.


- To get the usual(textbook) t test, you must specify that you are willing to assume that the variances are the same. This is done via the optional argument var.equal=T;
- 표준(교과서) t 검정을 얻으려면 두 분산이 동일하다고 가정할 것을 명시해야 합니다. 이는 선택적 인자 var.equal=T를 통해 수행됩니다.

In [5]:
t.test(expend~stature, var.equal=T)


	Two Sample t-test

data:  expend by stature
t = -3.9456, df = 20, p-value = 0.000799
alternative hypothesis: true difference in means between group lean and group obese is not equal to 0
95 percent confidence interval:
 -3.411451 -1.051796
sample estimates:
 mean in group lean mean in group obese 
           8.066154           10.297778 


- Notice that the degrees of freedom now has become a whole number, namely 13+9-2=20. The p-value has dropped slightly (from 0.14% to 0.08%) and the confidence interval is a litter narrower, but overall the changes are slight.
- 주의해야 할 점은 자유도가 이제 정수가 된 것입니다. 즉, 13+9-2=20입니다. p값은 약간 감소했습니다 (0.14%에서 0.08%로), 신뢰 구간은 조금 더 좁아졌지만, 전반적으로 변화는 미미합니다.

### 2. Comparison of Variances

- Two population variances <img src="https://latex.codecogs.com/svg.image?\sigma_1^2,\sigma_2^2">, sample sizes <img src="https://latex.codecogs.com/svg.image?n_1,n_2">, and sample variances <img src="https://latex.codecogs.com/svg.image?S_1^2,S_2^2"> repectively
- The following test statistic follows F distribution with degrees of freedom <img src="https://latex.codecogs.com/svg.image?(n_1-1,n_2-1)"> under the null hypothesis <img src="https://latex.codecogs.com/svg.image?\sigma_1^2=\sigma_2^2">

<center>
<img src="https://latex.codecogs.com/svg.image?F=\frac{\left(\frac{S_1^2}{\sigma_1^2}\right)}{\left(\frac{S_2^2}{\sigma_2^2}\right)}"><br>

|<img src="https://latex.codecogs.com/svg.image?H_0:\sigma_1^2=\sigma_2^2"> <br> <img src="https://latex.codecogs.com/svg.image?H_1:\sigma_1^2\neq\sigma_2^2">|<img src="https://latex.codecogs.com/svg.image?\frac{S_1^2}{S_2^2}>F_{n_1-1,n_2-1,\alpha/2}\;\;or\;\;\frac{S_1^2}{S_2^2}<F_{n_1-1,n_2-1,\alpha/2}\Rightarrow\;\;reject\;H_0">|
|---|---|
</center>



- Testing the assumption that the variances are the same

In [6]:
var.test(expend~stature)


	F test to compare two variances

data:  expend by stature
F = 0.78445, num df = 12, denom df = 8, p-value = 0.6797
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.1867876 2.7547991
sample estimates:
ratio of variances 
          0.784446 


- The test is not significant, so there is no evidence against the assumption that the variances are identical. However, the confidence interval is very wide. For small data sets such as this one, the assumption of constant variances largely a matter of belief.
- 검정 결과가 유의하지 않기 때문에 분산이 동일하다는 가정에 대한 증거가 없습니다. 그러나 신뢰 구간이 매우 넓습니다. 이와 같은 작은 데이터 집합의 경우, 일정한 분산의 가정은 대부분 믿음의 문제입니다.

### 3. Two-sample Wilcoxon test

- You might prefer a nonparametric test if you doubt the normal distribution assumptions of the t test. The two-sample Wilcoxon test is based on replacing the data by their rank(without regard yo grouping) and calculating the sum of the ranks in one group, thus reducing the problem to one of sampling n1 values without replacement from the numbers 1 to n1+n2.
- t 검정의 정규 분포 가정에 대해 의심이 들 경우 비모수 검정을 선호할 수 있습니다. 두 개의 표본 Wilcoxon 검정은 데이터를 그들의 순위로 대체하고(그룹화와 관계없이) 한 그룹의 순위 합계를 계산함으로써 문제를 n1과 n1+n2까지의 숫자에서 복원 없이 n1 값의 샘플링 문제로 축소시킵니다.

In [7]:
wilcox.test(expend~stature)

Warning message in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...):
"tie가 있어 정확한 p값을 계산할 수 없습니다"



	Wilcoxon rank sum test with continuity correction

data:  expend by stature
W = 12, p-value = 0.002122
alternative hypothesis: true location shift is not equal to 0


- The test statistic W is the sum of ranks in the first group minus its theoretical minimum.(i.e., it is zero if all the smallest values fall in the first group).
- 검정 통계량 W는 첫 번째 그룹의 순위 합계에서 그의 이론적 최소값을 뺀 것입니다. (즉, 가장 작은 값이 모두 첫 번째 그룹에 속하는 경우에는 0입니다).

## 03 Two-sample test(Paired samples)

### 1. The paired t test

- Paired tests are used when there are two measurements on the same experimental unit

|Sample from pop1|Sample from Pop2|<img src="https://latex.codecogs.com/svg.image?D_i=X_{i1}-X_{i2}">|
|:---:|:---:|:---:|
|<img src="https://latex.codecogs.com/svg.image?X_11"><br><img src="https://latex.codecogs.com/svg.image?X_21"><br><img src="https://latex.codecogs.com/svg.image?\vdots"><br><img src="https://latex.codecogs.com/svg.image?X_n1">|<img src="https://latex.codecogs.com/svg.image?X_12"><br><img src="https://latex.codecogs.com/svg.image?X_22"><br><img src="https://latex.codecogs.com/svg.image?\vdots"><br><img src="https://latex.codecogs.com/svg.image?X_n2">|<img src="https://latex.codecogs.com/svg.image?D_1=X_{11}-X_{12}"><br><img src="https://latex.codecogs.com/svg.image?D_2=X_{21}-X_{22}"><br><img src="https://latex.codecogs.com/svg.image?\vdots"><br><img src="https://latex.codecogs.com/svg.image?D_n=X_{n1}-X_{n2}">|

<img src="https://latex.codecogs.com/svg.image?\bar{D}=\sum{\frac{D_i}{n}}"><br>
<img src="https://latex.codecogs.com/svg.image?S_D^2=\sum\frac{(D_i-\bar{D})^2}{n-1}">

- Paired tests are used when there are two measurements on the same experimental unit.

|<img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=D_0"><br><img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2>D_0">|<img src="https://latex.codecogs.com/svg.image?\frac{\bar{D}-D_0}{S_d/\sqrt{n}}>t_{n-1,\alpha} \Rightarrow reject\;H_0">|
|:-:|:-:|
|<img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=D_0"><br><img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2<D_0">|<img src="https://latex.codecogs.com/svg.image?\frac{\bar{D}-D_0}{S_d/\sqrt{n}}<-t_{n-1,\alpha} \Rightarrow reject\;H_0">|
|<img src="https://latex.codecogs.com/svg.image?H_0:\mu_1-\mu_2=D_0"><br><img src="https://latex.codecogs.com/svg.image?H_1:\mu_1-\mu_2\neq D_0">|<img src="https://latex.codecogs.com/svg.image?\left\|\frac{\bar{D}-D_0}{S_d/\sqrt{n}}\right\|>t_{n-1,\alpha/2} \Rightarrow reject\;H_0">|

In [8]:
intake

pre  post
1  5260 3910
2  5470 4220
3  5640 3885
4  6180 5160
5  6390 5645
6  6515 4680
7  6805 5265
8  7515 5975
9  7515 6790
10 8230 6900
11 8770 7335

In [9]:
attach(intake)
t.test(pre, post, paired=T)


	Paired t-test

data:  pre and post
t = 11.941, df = 10, p-value = 3.059e-07
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 1074.072 1566.838
sample estimates:
mean difference 
       1320.455 


- The paired Wilcoxon test is the same as a one-sample Wilcoxon signed rank test on the differences.

In [10]:
wilcox.test(pre, post, paired=T)

Warning message in wilcox.test.default(pre, post, paired = T):
"tie가 있어 정확한 p값을 계산할 수 없습니다"



	Wilcoxon signed rank test with continuity correction

data:  pre and post
V = 66, p-value = 0.00384
alternative hypothesis: true location shift is not equal to 0
